[package]
edition.workspace = true
license.workspace = true
name = "codewen-analytics"
version.workspace = true

[lib]
doctest = false
name = "codewen_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codewen-app-server-protocol = { workspace = true }
codewen-git-utils = { workspace = true }
codewen-login = { workspace = true }
codewen-model-provider = { workspace = true }
codewen-plugin = { workspace = true }
codewen-protocol = { workspace = true }
codewen-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
codewen-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
