[package]
edition.workspace = true
license.workspace = true
name = "codewen-prompts"
version.workspace = true

[lib]
doctest = false
name = "codewen_prompts"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
codewen-context-fragments = { workspace = true }
codewen-git-utils = { workspace = true }
codewen-execpolicy = { workspace = true }
codewen-protocol = { workspace = true }
codewen-utils-absolute-path = { workspace = true }
codewen-utils-template = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
