[package]
edition.workspace = true
license.workspace = true
name = "codewen-model-provider-info"
version.workspace = true

[lib]
doctest = false
name = "codewen_model_provider_info"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codewen-api = { workspace = true }
codewen-protocol = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
codewen-utils-absolute-path = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
