[package]
edition.workspace = true
license.workspace = true
name = "codewen-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
codewen-protocol = { workspace = true }
codewen-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
